import { Database, Search, Mail, ShoppingCart, Users, BarChart3, Settings, FolderOpen, User, Home, FileText, Briefcase, Clock, TrendingUp, Link, ChevronDown, Sparkles, ArrowRightLeft, Shield, Lock, Share2, BookOpen, Compass, Plug, Table2, MessageSquare } from "lucide-react"
import type { DataSourceCategory, NavigationItem, DataSource } from "@/types"

export const NAVIGATION_ITEMS: NavigationItem[] = [
  { id: "welcome", title: "Welcome", icon: Home },
  { id: "dashboards", title: "Dashboards", icon: BarChart3 },
  { id: "analytics", title: "Analytics", icon: BarChart3 },
]

export const DATA_SOURCE_CATEGORIES: DataSourceCategory[] = [
  { id: "all", name: "All", connected: 2, total: 15 },
  { id: "connected", name: "Connected", connected: 2, total: 2 },
  { id: "analytics", name: "Analytics", connected: 0, total: 3 },
  { id: "advertising", name: "Ads", connected: 1, total: 3 },
  { id: "email", name: "Email", connected: 1, total: 3 },
  { id: "ecommerce", name: "Commerce", connected: 0, total: 3 },
  { id: "social", name: "Social", connected: 0, total: 3 },
]

export const DATA_SOURCES: DataSource[] = [
  { id: "google-ads", name: "Google Ads", category: "advertising", connected: true, icon: Search },
  { id: "meta-ads", name: "Meta Ads", category: "advertising", connected: false, icon: User },
  { id: "linkedin-ads", name: "LinkedIn Ads", category: "advertising", connected: false, icon: User },
  { id: "mailchimp", name: "Mailchimp", category: "email", connected: false, icon: Mail },
  { id: "klaviyo", name: "Klaviyo", category: "email", connected: true, icon: Mail },
  { id: "sendgrid", name: "SendGrid", category: "email", connected: false, icon: Mail },
  { id: "shopify", name: "Shopify", category: "ecommerce", connected: false, icon: ShoppingCart },
  { id: "woocommerce", name: "WooCommerce", category: "ecommerce", connected: false, icon: ShoppingCart },
  { id: "magento", name: "Magento", category: "ecommerce", connected: false, icon: ShoppingCart },
]

export const STEP_IDS = {
  SETUP: "setup",
  SOURCES: "sources",
  ACCOUNTS: "accounts",
  MODEL: "model",
} as const

export const PROCESSING_STEPS = [
  { id: "connect", name: "Connect API", icon: Database },
  { id: "extract", name: "Extract Data", icon: Database },
  { id: "process", name: "Process & Clean", icon: Settings },
  { id: "dashboard", name: "Build Dashboard", icon: BarChart3 },
] as const

export const DATA_SOURCE_PROCESSING = [
  { id: "google-ads", name: "Google Ads", symbol: "G", color: "bg-blue-500" },
  { id: "meta-ads", name: "Meta Ads", symbol: "M", color: "bg-blue-600" },
  { id: "klaviyo", name: "Klaviyo", symbol: "K", color: "bg-purple-500" },
] as const

export const ANIMATION_DURATIONS = {
  FAST: 150,
  NORMAL: 200,
  SLOW: 300,
  EXTRA_SLOW: 500,
} as const

export const DEBOUNCE_DELAYS = {
  SEARCH: 300,
  RESIZE: 100,
  SCROLL: 50,
} as const

export const VALIDATION_RULES = {
  MIN_APP_NAME_LENGTH: 2,
  MAX_APP_NAME_LENGTH: 50,
  MIN_TABLE_NAME_LENGTH: 2,
  MAX_TABLE_NAME_LENGTH: 30,
} as const

export const MOCK_DATA_FIELDS = [
  { id: "user_id", name: "User ID", type: "string", required: true, description: "Unique identifier for users" },
  { id: "email", name: "Email", type: "string", required: true, description: "User email address" },
  { id: "created_at", name: "Created At", type: "datetime", required: true, description: "Account creation timestamp" },
  { id: "last_login", name: "Last Login", type: "datetime", required: false, description: "Last login timestamp" },
  {
    id: "subscription_type",
    name: "Subscription",
    type: "string",
    required: false,
    description: "User subscription level",
  },
] as const

export const MOCK_ACCOUNTS = [
  {
    id: "main-business",
    name: "Main Business Account",
    email: "ads@company.com",
    accounts: [
      { id: "ecommerce-campaign", name: "E-commerce Store Campaign", status: "active" as const },
      { id: "brand-awareness", name: "Brand Awareness Account", status: "active" as const },
      { id: "local-business", name: "Local Business Ads", status: "inactive" as const },
    ],
  },
  {
    id: "agency-account",
    name: "Agency Account",
    email: "agency@marketing.com",
    accounts: [
      { id: "client-a", name: "Client Campaign A", status: "active" as const },
      { id: "client-b", name: "Client Campaign B", status: "active" as const },
    ],
  },
] as const

export const PROCESSING_STATES = {
  PENDING: "pending",
  PROCESSING: "processing",
  COMPLETED: "completed",
  ERROR: "error",
} as const

export const ACCOUNT_STATUSES = {
  ACTIVE: "active",
  INACTIVE: "inactive",
  SUSPENDED: "suspended",
} as const

export const TREE_NAVIGATION = [
  {
    id: "search",
    title: "Search",
    icon: Search,
    type: "search",
    expanded: false,
  },
  {
    id: "ai-agent",
    title: "AI Agent",
    icon: Sparkles,
    type: "file",
    expanded: false,
  },
  {
    id: "analytics-section",
    title: "Analytics",
    icon: BarChart3,
    type: "section",
    expanded: false,
  },
  {
    id: "chats",
    title: "Chats",
    icon: FolderOpen,
    type: "folder",
    expanded: false,
    children: [
      {
        id: "chat-compare-ad-spend",
        title: "Compare Q4 vs Q1 ad spend by channel",
        icon: MessageSquare,
        type: "file",
        status: "private",
        tag: "Analysis",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        description: "Side-by-side comparison of Q4 and Q1 advertising spend across Google, Meta, and LinkedIn channels.",
        relatedTo: [{ id: "cross-channel-dashboard", title: "Cross Channel Dashboard", type: "dashboard" }],
      },
      {
        id: "chat-conversion-drop",
        title: "Why did conversion rate drop last week",
        icon: MessageSquare,
        type: "file",
        status: "shared",
        tag: "Investigation",
        updated: "Dec 15, 2024",
        updatedBy: "Emma Davis",
        description: "Investigating the 12% conversion rate decline observed in week 49 across paid channels.",
        relatedTo: [{ id: "marketing-performance-dashboard", title: "Marketing Performance", type: "dashboard" }],
        sharedWith: [{ id: "user-emma", name: "Emma Davis" }, { id: "user-john", name: "John Smith" }, { id: "user-admin", name: "System Admin" }],
        sharedBy: "Emma Davis",
      },
      {
        id: "chat-cohort-analysis",
        title: "Build a cohort analysis for new users",
        icon: MessageSquare,
        type: "file",
        status: "private",
        tag: "Analysis",
        updated: "Dec 14, 2024",
        updatedBy: "System Admin",
        description: "Creating retention cohorts for users acquired through different marketing channels in Q4.",
      },
      {
        id: "chat-top-keywords",
        title: "Summarize top performing keywords",
        icon: MessageSquare,
        type: "file",
        status: "shared",
        tag: "Report",
        updated: "Dec 13, 2024",
        updatedBy: "John Smith",
        description: "Ranking and analysis of highest-converting search keywords across Google Ads campaigns.",
        relatedTo: [{ id: "cross-channel-dashboard", title: "Cross Channel Dashboard", type: "dashboard" }],
        sharedWith: [{ id: "user-john", name: "John Smith" }, { id: "user-admin", name: "System Admin" }],
        sharedBy: "John Smith",
      },
      {
        id: "chat-revenue-attribution",
        title: "Show me revenue attribution by source",
        icon: MessageSquare,
        type: "file",
        status: "private",
        tag: "Analysis",
        updated: "Dec 12, 2024",
        updatedBy: "System Admin",
        description: "Multi-touch attribution model showing revenue contribution from each marketing channel.",
      },
      {
        id: "chat-email-dashboard",
        title: "Create a dashboard for email campaigns",
        icon: MessageSquare,
        type: "file",
        status: "shared",
        tag: "Dashboard",
        updated: "Dec 11, 2024",
        updatedBy: "Emma Davis",
        description: "Building a new dashboard to track open rates, click rates, and conversions for email campaigns.",
        sharedWith: [{ id: "user-emma", name: "Emma Davis" }, { id: "user-admin", name: "System Admin" }, { id: "user-john", name: "John Smith" }, { id: "user-sarah", name: "Sarah Chen" }],
        sharedBy: "Emma Davis",
      },
      {
        id: "chat-roas-meta",
        title: "What's the ROAS for Meta Ads this month",
        icon: MessageSquare,
        type: "file",
        status: "private",
        tag: "Analysis",
        updated: "Dec 10, 2024",
        updatedBy: "System Admin",
        description: "Calculating return on ad spend for Meta Ads campaigns running in December.",
        relatedTo: [{ id: "marketing-performance-dashboard", title: "Marketing Performance", type: "dashboard" }],
      },
      {
        id: "chat-weekly-report",
        title: "Draft a weekly marketing report",
        icon: MessageSquare,
        type: "file",
        status: "shared",
        tag: "Report",
        updated: "Dec 9, 2024",
        updatedBy: "John Smith",
        description: "Automated weekly summary of KPIs, spend, and highlights for the marketing team.",
        sharedWith: [{ id: "user-john", name: "John Smith" }, { id: "user-emma", name: "Emma Davis" }],
        sharedBy: "John Smith",
      },
      { id: "chats-show-all", title: "Show all 24 chats", icon: MessageSquare, type: "more" },
    ],
  },
  {
    id: "dashboards",
    title: "Dashboards",
    icon: FolderOpen,
    type: "folder",
    expanded: true,
    children: [
      {
        id: "dashboard-templates",
        title: "Dashboard Templates",
        icon: BarChart3,
        type: "file",
        expanded: false,
        status: "template",
        tag: "Templates",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        description: "Pre-built dashboard templates for quick setup across common use cases.",
      },
      {
        id: "cross-channel-dashboard",
        title: "Cross Channel Dashboard",
        icon: BarChart3,
        type: "file",
        expanded: false,
        status: "template",
        tag: "Analytics",
        updated: "Dec 15, 2024",
        updatedBy: "John Smith",
        description: "Unified view of paid search, social, and display performance across all channels.",
        relatedTo: [
          { id: "google-ads-connection", title: "Google Ads", type: "connection" },
          { id: "meta-ads-connection", title: "Meta Ads", type: "connection" },
        ],
      },
      {
        id: "ecommerce-dashboard",
        title: "E-commerce Dashboard",
        icon: BarChart3,
        type: "file",
        expanded: false,
        status: "private",
        tag: "E-commerce",
        updated: "Dec 12, 2024",
        updatedBy: "Emma Davis",
        description: "Sales funnel, revenue trends, and product performance metrics.",
      },
      {
        id: "marketing-performance-dashboard",
        title: "Marketing Performance",
        icon: BarChart3,
        type: "file",
        expanded: false,
        status: "shared",
        tag: "Marketing",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        description: "Campaign ROI, spend efficiency, and audience engagement overview.",
        relatedTo: [
          { id: "meta-ads-connection", title: "Meta Ads", type: "connection" },
          { id: "google-ads-connection", title: "Google Ads", type: "connection" },
        ],
      },
    ],
  },
  {
    id: "reports",
    title: "Reports",
    icon: FolderOpen,
    type: "folder",
    expanded: false,
    children: [
      {
        id: "marketing-report-1",
        title: "Monthly Performance Report",
        icon: FileText,
        type: "file",
        expanded: false,
        status: "template",
        tag: "Monthly",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        description: "Auto-generated performance summary across all active campaigns.",
        relatedTo: [{ id: "cross-channel-dashboard", title: "Cross Channel Dashboard", type: "dashboard" }],
      },
      {
        id: "marketing-report-2",
        title: "Campaign Analysis Report",
        icon: FileText,
        type: "file",
        expanded: false,
        status: "private",
        tag: "Campaigns",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        description: "Deep-dive analysis of individual campaign performance and optimizations.",
      },
      {
        id: "marketing-report-3",
        title: "ROI Analysis Report",
        icon: FileText,
        type: "file",
        expanded: false,
        status: "shared",
        tag: "ROI",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        description: "Return on investment breakdown by channel, campaign, and creative.",
        relatedTo: [
          { id: "marketing-performance-dashboard", title: "Marketing Performance", type: "dashboard" },
          { id: "cross-channel-dashboard", title: "Cross Channel Dashboard", type: "dashboard" },
        ],
      },
    ],
  },
  {
    id: "data-pipelines-section",
    title: "Data Pipelines",
    icon: Database,
    type: "section",
    expanded: false,
  },
  {
    id: "connections",
    title: "Connections",
    icon: FolderOpen,
    type: "folder",
    expanded: false,
    children: [
      {
        id: "google-ads-connection",
        title: "Google Ads",
        icon: Search,
        type: "file",
        expanded: false,
        status: "shared",
        tag: "Google Ads",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        account: "ads@company.com",
      },
      {
        id: "meta-ads-connection",
        title: "Meta Ads",
        icon: User,
        type: "file",
        expanded: false,
        status: "shared",
        tag: "Meta Ads",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        account: "ads@company.com",
      },
      {
        id: "linkedin-ads-connection",
        title: "LinkedIn Ads",
        icon: Briefcase,
        type: "file",
        expanded: false,
        status: "shared",
        tag: "LinkedIn Ads",
        updated: "Dec 10, 2024",
        updatedBy: "John Smith",
        account: "marketing@company.com",
      },
      {
        id: "tiktok-ads-connection",
        title: "TikTok Ads",
        icon: User,
        type: "file",
        expanded: false,
        status: "private",
        tag: "TikTok Ads",
        updated: "Dec 8, 2024",
        updatedBy: "Emma Davis",
        account: "social@company.com",
      },
      {
        id: "twitter-ads-connection",
        title: "Twitter Ads",
        icon: User,
        type: "file",
        expanded: false,
        status: "private",
        tag: "Twitter Ads",
        updated: "Dec 5, 2024",
        updatedBy: "John Smith",
        account: "agency@marketing.com",
      },
    ],
  },
  {
    id: "data-explorer",
    title: "Data Explorer",
    icon: FolderOpen,
    type: "folder",
    expanded: false,
    children: [
      {
        id: "data-table-1",
        title: "Customer Segmentation",
        icon: Database,
        type: "file",
        expanded: false,
        status: "template",
        tag: "Segmentation",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        description: "RFM-based customer segments with behavioral clustering.",
        relatedTo: [{ id: "google-ads-connection", title: "Google Ads", type: "connection" }],
      },
      {
        id: "data-table-2",
        title: "Conversion Funnel Analysis",
        icon: Database,
        type: "file",
        expanded: false,
        status: "template",
        tag: "Funnel",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        description: "Step-by-step funnel drop-off analysis with attribution paths.",
        relatedTo: [{ id: "cross-channel-dashboard", title: "Cross Channel Dashboard", type: "dashboard" }],
      },
      {
        id: "data-table-3",
        title: "Cohort Analysis",
        icon: Database,
        type: "file",
        expanded: false,
        status: "template",
        tag: "Cohort",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
        description: "Time-based cohort retention and lifetime value analysis.",
      },
    ],
  },
  {
    id: "recipes",
    title: "Recipes",
    icon: FolderOpen,
    type: "folder",
    expanded: false,
    children: [
      {
        id: "recipe-audience-brand",
        title: "Audience & Brand",
        icon: FolderOpen,
        type: "folder",
        expanded: false,
        children: [
          // Level 2 folder first
          {
            id: "recipe-behavioral-analysis",
            title: "Behavioral Analysis",
            icon: FolderOpen,
            type: "folder",
            expanded: false,
            children: [
              // Level 3 folder first
              {
                id: "recipe-engagement-scoring",
                title: "Engagement Scoring",
                icon: FolderOpen,
                type: "folder",
                expanded: false,
                children: [
                  // Level 4 folder first
                  {
                    id: "recipe-channel-attribution",
                    title: "Channel Attribution",
                    icon: FolderOpen,
                    type: "folder",
                    expanded: false,
                    children: [
                      // Level 5 folder first
                      {
                        id: "recipe-predictive-models",
                        title: "Predictive Models",
                        icon: FolderOpen,
                        type: "folder",
                        expanded: false,
                        children: [
                          { id: "recipe-churn-prediction", title: "Churn Prediction", icon: FileText, type: "file", tag: "ML", status: "private" as const, updated: "Dec 6, 2024", updatedBy: "Emma Davis", dataTable: "churn_prediction_recipe" },
                          { id: "recipe-ltv-forecast", title: "LTV Forecast Model", icon: FileText, type: "file", tag: "ML", status: "template" as const, updated: "Dec 5, 2024", updatedBy: "System Admin", dataTable: "ltv_forecast_model_recipe" },
                          { id: "recipe-propensity-scoring", title: "Purchase Propensity Score", icon: FileText, type: "file", tag: "ML", status: "shared" as const, updated: "Dec 4, 2024", updatedBy: "John Smith", dataTable: "purchase_propensity_score_recipe" },
                        ],
                      },
                      // Level 4 files
                      { id: "recipe-first-touch-attr", title: "First Touch Attribution", icon: FileText, type: "file", tag: "Attribution", status: "template" as const, updated: "Dec 8, 2024", updatedBy: "System Admin", dataTable: "first_touch_attribution_recipe" },
                      { id: "recipe-multi-touch-attr", title: "Multi-Touch Attribution", icon: FileText, type: "file", tag: "Attribution", status: "shared" as const, updated: "Dec 7, 2024", updatedBy: "John Smith", dataTable: "multi_touch_attribution_recipe" },
                    ],
                  },
                  // Level 3 files
                  { id: "recipe-lead-scoring-model", title: "Lead Scoring Model", icon: FileText, type: "file", tag: "Scoring", status: "private" as const, updated: "Dec 10, 2024", updatedBy: "Emma Davis", dataTable: "lead_scoring_model_recipe" },
                  { id: "recipe-content-engagement", title: "Content Engagement Score", icon: FileText, type: "file", tag: "Scoring", status: "shared" as const, updated: "Dec 9, 2024", updatedBy: "John Smith", dataTable: "content_engagement_score_recipe" },
                ],
              },
              // Level 2 files
              { id: "recipe-session-flow", title: "Session Flow Analysis", icon: FileText, type: "file", tag: "Behavior", status: "shared" as const, updated: "Dec 13, 2024", updatedBy: "John Smith", dataTable: "session_flow_analysis_recipe" },
              { id: "recipe-page-interaction", title: "Page Interaction Heatmap", icon: FileText, type: "file", tag: "Behavior", status: "template" as const, updated: "Dec 11, 2024", updatedBy: "System Admin", dataTable: "page_interaction_heatmap_recipe" },
            ],
          },
          // Level 1 files
          { id: "recipe-audience-segmentation", title: "Audience Segmentation by Source", icon: FileText, type: "file", tag: "Audience", status: "shared" as const, updated: "Dec 14, 2024", updatedBy: "Emma Davis", dataTable: "audience_segmentation_by_source_recipe" },
          { id: "recipe-brand-awareness", title: "Brand Awareness Metrics", icon: FileText, type: "file", tag: "Brand", status: "template" as const, updated: "Dec 12, 2024", updatedBy: "System Admin", dataTable: "brand_awareness_metrics_recipe" },
          { id: "recipe-cross-channel-attribution", title: "Cross Channel Attribution Model", icon: FileText, type: "file", tag: "Attribution", status: "shared" as const, updated: "Dec 10, 2024", updatedBy: "John Smith", dataTable: "cross_channel_attribution_model_recipe" },
          { id: "recipe-email-engagement", title: "Email Campaign Engagement", icon: FileText, type: "file", tag: "Email", status: "private" as const, updated: "Dec 8, 2024", updatedBy: "System Admin", dataTable: "email_campaign_engagement_recipe" },
        ],
      },
      {
        id: "recipe-channel-performance",
        title: "Channel Performance",
        icon: FolderOpen,
        type: "folder",
        expanded: false,
        children: [
          {
            id: "recipe-paid-ads-ga-basic",
            title: "Paid Ads Google Analytics - Basic Analytics",
            icon: FileText,
            type: "file",
            tag: "Google Analytics",
            status: "template" as const,
            updated: "Dec 15, 2024",
            updatedBy: "System Admin",
            dataTable: "paid_ads_google_analytics_basic_analytics_recipe",
            description: "Core paid ads metrics from Google Analytics including sessions, bounce rate, and conversions.",
          },
          {
            id: "recipe-paid-ads-ga-campaign",
            title: "Paid Ads Google Analytics - Campaign Performance",
            icon: FileText,
            type: "file",
            tag: "Google Analytics",
            status: "template" as const,
            updated: "Dec 15, 2024",
            updatedBy: "System Admin",
            dataTable: "paid_ads_google_analytics_campaign_performance_recipe",
            description: "Campaign-level performance breakdown with cost and revenue attribution.",
          },
          {
            id: "recipe-int-tiktok-preview",
            title: "Int TikTok Ads Preview Prep",
            icon: FileText,
            type: "file",
            tag: "TikTok",
            status: "private" as const,
            updated: "Dec 13, 2024",
            updatedBy: "Emma Davis",
            dataTable: "int_tiktok_ads_preview_prep",
            description: "Intermediate staging table for TikTok ad creative preview data.",
          },
          {
            id: "recipe-meta-ads-funnel",
            title: "Meta Ads Conversion Funnel",
            icon: FileText,
            type: "file",
            tag: "Meta",
            status: "shared" as const,
            updated: "Dec 11, 2024",
            updatedBy: "John Smith",
            dataTable: "meta_ads_conversion_funnel_recipe",
            description: "Full-funnel view from impression to purchase for Meta ad campaigns.",
          },
          {
            id: "recipe-linkedin-lead-quality",
            title: "LinkedIn Lead Quality Score",
            icon: FileText,
            type: "file",
            tag: "LinkedIn",
            status: "private" as const,
            updated: "Dec 9, 2024",
            updatedBy: "System Admin",
            dataTable: "linkedin_lead_quality_score_recipe",
            description: "Scores LinkedIn-generated leads by firmographic and engagement signals.",
          },
        ],
      },
      {
        id: "recipe-google-ads",
        title: "Google Ads",
        icon: FolderOpen,
        type: "folder",
        expanded: false,
        children: [
          {
            id: "recipe-gads-keyword-perf",
            title: "Google Ads Keyword Performance",
            icon: FileText,
            type: "file",
            tag: "Keywords",
            status: "template" as const,
            updated: "Dec 15, 2024",
            updatedBy: "System Admin",
            dataTable: "google_ads_keyword_performance_recipe",
            description: "Keyword-level CPC, CTR, conversion rate, and quality score analysis.",
          },
          {
            id: "recipe-gads-campaign-roas",
            title: "Google Ads Campaign ROAS",
            icon: FileText,
            type: "file",
            tag: "ROAS",
            status: "shared" as const,
            updated: "Dec 14, 2024",
            updatedBy: "John Smith",
            dataTable: "google_ads_campaign_roas_recipe",
            description: "Return on ad spend by campaign with budget pacing and forecast.",
          },
          {
            id: "recipe-gads-search-terms",
            title: "Google Ads Search Terms Analysis",
            icon: FileText,
            type: "file",
            tag: "Search",
            status: "template" as const,
            updated: "Dec 13, 2024",
            updatedBy: "System Admin",
            dataTable: "google_ads_search_terms_analysis_recipe",
            description: "Search term report with negative keyword recommendations.",
          },
          {
            id: "recipe-gads-audience-insights",
            title: "Google Ads Audience Insights",
            icon: FileText,
            type: "file",
            tag: "Audience",
            status: "private" as const,
            updated: "Dec 11, 2024",
            updatedBy: "Emma Davis",
            dataTable: "google_ads_audience_insights_recipe",
            description: "Audience segment performance with demographic and interest breakdowns.",
          },
        ],
      },
      {
        id: "recipe-weekly-kpi-rollup",
        title: "Weekly KPI Rollup",
        icon: FileText,
        type: "file",
        tag: "KPI",
        status: "shared" as const,
        updated: "Dec 15, 2024",
        updatedBy: "John Smith",
        dataTable: "weekly_kpi_rollup_recipe",
      },
      {
        id: "recipe-customer-ltv",
        title: "Customer Lifetime Value",
        icon: FileText,
        type: "file",
        tag: "Revenue",
        status: "template" as const,
        updated: "Dec 14, 2024",
        updatedBy: "System Admin",
        dataTable: "customer_lifetime_value_recipe",
      },
      {
        id: "recipe-spend-vs-revenue",
        title: "Spend vs Revenue Summary",
        icon: FileText,
        type: "file",
        tag: "Finance",
        status: "private" as const,
        updated: "Dec 13, 2024",
        updatedBy: "Emma Davis",
        dataTable: "spend_vs_revenue_summary_recipe",
      },
    ],
  },
  {
    id: "admin",
    title: "Admin",
    icon: FolderOpen,
    type: "folder",
    expanded: false,
    children: [
      {
        id: "service-desk",
        title: "Service Desk",
        icon: Settings,
        type: "file",
        expanded: false,
        status: "template",
        tag: "Support",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
      },
      {
        id: "dataflow",
        title: "Dataflow",
        icon: Database,
        type: "file",
        expanded: false,
        status: "template",
        tag: "Data Flow",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
      },
      {
        id: "billing",
        title: "Billing",
        icon: Users,
        type: "file",
        expanded: false,
        status: "template",
        tag: "Billing",
        updated: "Dec 15, 2024",
        updatedBy: "System Admin",
      },
    ],
  },
  {
    id: "latest-section",
    title: "Latest",
    icon: Clock,
    type: "section",
    expanded: false,
  },
  {
    id: "latest-item-1",
    title: "Campaign Performance",
    icon: TrendingUp,
    type: "file",
    expanded: false,
  },
  {
    id: "latest-item-2",
    title: "New Connections",
    icon: Link,
    type: "file",
    expanded: false,
  },
  {
    id: "latest-item-3",
    title: "Recent Reports",
    icon: FileText,
    type: "file",
    expanded: false,
  },
  {
    id: "latest-more",
    title: "More",
    icon: ChevronDown,
    type: "more",
    expanded: false,
  },
] as const

export const CATEGORY_GROUPS = [
  { id: "ai-agent",        label: "AI Agent",       icon: Sparkles,       navItemIds: ["ai-agent", "chats", "chat-compare-ad-spend", "chat-conversion-drop", "chat-cohort-analysis", "chat-top-keywords", "chat-revenue-attribution", "chat-email-dashboard", "chat-roas-meta", "chat-weekly-report"] },
  { id: "dashboards",      label: "Dashboards",     icon: BarChart3,      navItemIds: ["dashboards"] },
  { id: "connections",     label: "Connections",    icon: Plug,           navItemIds: ["connections", "dest-warehouse", "dest-analytics", "dest-cloud"] },
  { id: "tables",          label: "Tables",         icon: Table2,         navItemIds: ["data-explorer", "tbl-customer-ltv", "tbl-customer-profiles", "tbl-campaign-metrics", "tbl-channel-attribution", "tbl-session-events", "tbl-pageview-logs", "tbl-orders", "tbl-products", "tbl-transactions"] },
  { id: "recipes",         label: "Recipes",        icon: ArrowRightLeft, navItemIds: ["recipes", "recipe-audience-brand", "recipe-channel-performance", "recipe-google-ads", "recipe-audience-segmentation", "recipe-brand-awareness", "recipe-cross-channel-attribution", "recipe-email-engagement", "recipe-paid-ads-ga-basic", "recipe-paid-ads-ga-campaign", "recipe-int-tiktok-preview", "recipe-meta-ads-funnel", "recipe-linkedin-lead-quality", "recipe-gads-keyword-perf", "recipe-gads-campaign-roas", "recipe-gads-search-terms", "recipe-gads-audience-insights"] },
  { id: "data-governance", label: "Governance",     icon: Shield,         navItemIds: ["naming-convention", "rules", "mission-control"] },
  { id: "admin",           label: "Admin",          icon: Settings,       navItemIds: ["admin"] },
]

export const CATEGORY_TREES: Record<string, any[]> = {
  "ai-agent": [
    { id: "personal-chats", title: "Personal", icon: Lock, type: "folder", children: [
      { id: "chat-compare-ad-spend", title: "Compare Q4 vs Q1 ad spend by channel", icon: MessageSquare, type: "file" },
      { id: "chat-cohort-analysis", title: "Build a cohort analysis for new users", icon: MessageSquare, type: "file" },
      { id: "chat-revenue-attribution", title: "Show me revenue attribution by source", icon: MessageSquare, type: "file" },
      { id: "chat-roas-meta", title: "What's the ROAS for Meta Ads this month", icon: MessageSquare, type: "file" },
    ]},
    { id: "shared-chats", title: "Shared", icon: Share2, type: "folder", children: [
      { id: "chat-conversion-drop", title: "Why did conversion rate drop last week", icon: MessageSquare, type: "file" },
      { id: "chat-top-keywords", title: "Summarize top performing keywords", icon: MessageSquare, type: "file" },
      { id: "chat-email-dashboard", title: "Create a dashboard for email campaigns", icon: MessageSquare, type: "file" },
      { id: "chat-weekly-report", title: "Draft a weekly marketing report", icon: MessageSquare, type: "file" },
    ]},
    { id: "recent-chats-section", title: "Recent", type: "section" },
    { id: "chat-compare-ad-spend", title: "Compare Q4 vs Q1 ad spend by channel", icon: MessageSquare, type: "file" },
    { id: "chat-conversion-drop", title: "Why did conversion rate drop last week", icon: MessageSquare, type: "file" },
    { id: "chat-cohort-analysis", title: "Build a cohort analysis for new users", icon: MessageSquare, type: "file" },
    { id: "chat-top-keywords", title: "Summarize top performing keywords", icon: MessageSquare, type: "file" },
    { id: "chat-revenue-attribution", title: "Show me revenue attribution by source", icon: MessageSquare, type: "file" },
    { id: "chat-email-dashboard", title: "Create a dashboard for email campaigns", icon: MessageSquare, type: "file" },
    { id: "chat-roas-meta", title: "What's the ROAS for Meta Ads this month", icon: MessageSquare, type: "file" },
    { id: "chat-weekly-report", title: "Draft a weekly marketing report", icon: MessageSquare, type: "file" },
  ],
  "dashboards": [
    { id: "marketing-dashboards", title: "Marketing", icon: FolderOpen, type: "folder", children: [
      { id: "cross-channel-dashboard", title: "Cross Channel Dashboard", icon: BarChart3, type: "file" },
      { id: "marketing-performance-dashboard", title: "Marketing Performance", icon: BarChart3, type: "file" },
    ]},
    { id: "ecommerce-dashboards", title: "E-commerce", icon: FolderOpen, type: "folder", children: [
      { id: "ecommerce-dashboard", title: "E-commerce Dashboard", icon: BarChart3, type: "file" },
    ]},
    { id: "templates-dashboards", title: "Templates", icon: FolderOpen, type: "folder", children: [
      { id: "dashboard-templates", title: "Dashboard Templates", icon: BarChart3, type: "file" },
    ]},
  ],
  "connections": [
    { id: "sources-folder", title: "Sources", icon: FolderOpen, type: "folder", children: [
      { id: "google-ads-connection", title: "Google Ads", icon: Search, type: "file" },
      { id: "meta-ads-connection", title: "Meta Ads", icon: User, type: "file" },
      { id: "linkedin-ads-connection", title: "LinkedIn Ads", icon: Briefcase, type: "file" },
      { id: "tiktok-ads-connection", title: "TikTok Ads", icon: User, type: "file" },
      { id: "twitter-ads-connection", title: "Twitter Ads", icon: User, type: "file" },
    ]},
    { id: "destinations-folder", title: "Destinations", icon: FolderOpen, type: "folder", children: [
      { id: "dest-warehouse", title: "Data Warehouse", icon: Database, type: "file" },
      { id: "dest-analytics", title: "Analytics DB", icon: Database, type: "file" },
      { id: "dest-cloud", title: "Cloud Storage", icon: Database, type: "file" },
    ]},
    { id: "recent-connections-section", title: "Recent", type: "section" },
    { id: "recent-google-ads-connection", title: "Google Ads", icon: Search, type: "file" },
    { id: "recent-meta-ads-connection", title: "Meta Ads", icon: User, type: "file" },
    { id: "recent-linkedin-ads-connection", title: "LinkedIn Ads", icon: Briefcase, type: "file" },
  ],
  "tables": [
    { id: "customer-tables", title: "Customers", icon: FolderOpen, type: "folder", children: [
      { id: "data-table-1", title: "Customer Segmentation", icon: Table2, type: "file" },
      { id: "tbl-customer-ltv", title: "Customer LTV", icon: Table2, type: "file" },
      { id: "tbl-customer-profiles", title: "Customer Profiles", icon: Table2, type: "file" },
    ]},
    { id: "marketing-tables", title: "Marketing", icon: FolderOpen, type: "folder", children: [
      { id: "data-table-2", title: "Conversion Funnel Analysis", icon: Table2, type: "file" },
      { id: "tbl-campaign-metrics", title: "Campaign Metrics", icon: Table2, type: "file" },
      { id: "tbl-channel-attribution", title: "Channel Attribution", icon: Table2, type: "file" },
    ]},
    { id: "analytics-tables", title: "Analytics", icon: FolderOpen, type: "folder", children: [
      { id: "data-table-3", title: "Cohort Analysis", icon: Table2, type: "file" },
      { id: "tbl-session-events", title: "Session Events", icon: Table2, type: "file" },
      { id: "tbl-pageview-logs", title: "Pageview Logs", icon: Table2, type: "file" },
    ]},
    { id: "ecommerce-tables", title: "E-commerce", icon: FolderOpen, type: "folder", children: [
      { id: "tbl-orders", title: "Orders", icon: Table2, type: "file" },
      { id: "tbl-products", title: "Products", icon: Table2, type: "file" },
      { id: "tbl-transactions", title: "Transactions", icon: Table2, type: "file" },
    ]},
    { id: "recent-tables-section", title: "Recent", type: "section" },
    { id: "recent-data-table-1", title: "Customer Segmentation", icon: Table2, type: "file" },
    { id: "recent-data-table-2", title: "Conversion Funnel Analysis", icon: Table2, type: "file" },
    { id: "recent-tbl-orders", title: "Orders", icon: Table2, type: "file" },
  ],
  "recipes": [
    { id: "recipe-audience-brand", title: "Audience & Brand", icon: FolderOpen, type: "folder", children: [
      { id: "recipe-behavioral-analysis", title: "Behavioral Analysis", icon: FolderOpen, type: "folder", children: [
        { id: "recipe-engagement-scoring", title: "Engagement Scoring", icon: FolderOpen, type: "folder", children: [
          { id: "recipe-channel-attribution", title: "Channel Attribution", icon: FolderOpen, type: "folder", children: [
            { id: "recipe-predictive-models", title: "Predictive Models", icon: FolderOpen, type: "folder", children: [
              { id: "recipe-churn-prediction", title: "Churn Prediction", icon: FileText, type: "file" },
              { id: "recipe-ltv-forecast", title: "LTV Forecast Model", icon: FileText, type: "file" },
              { id: "recipe-propensity-scoring", title: "Purchase Propensity Score", icon: FileText, type: "file" },
            ]},
            { id: "recipe-first-touch-attr", title: "First Touch Attribution", icon: FileText, type: "file" },
            { id: "recipe-multi-touch-attr", title: "Multi-Touch Attribution", icon: FileText, type: "file" },
          ]},
          { id: "recipe-lead-scoring-model", title: "Lead Scoring Model", icon: FileText, type: "file" },
          { id: "recipe-content-engagement", title: "Content Engagement Score", icon: FileText, type: "file" },
        ]},
        { id: "recipe-session-flow", title: "Session Flow Analysis", icon: FileText, type: "file" },
        { id: "recipe-page-interaction", title: "Page Interaction Heatmap", icon: FileText, type: "file" },
      ]},
      { id: "recipe-audience-segmentation", title: "Audience Segmentation by Source", icon: FileText, type: "file" },
      { id: "recipe-brand-awareness", title: "Brand Awareness Metrics", icon: FileText, type: "file" },
      { id: "recipe-cross-channel-attribution", title: "Cross Channel Attribution Model", icon: FileText, type: "file" },
      { id: "recipe-email-engagement", title: "Email Campaign Engagement", icon: FileText, type: "file" },
    ]},
    { id: "recipe-channel-performance", title: "Channel Performance", icon: FolderOpen, type: "folder", children: [
      { id: "recipe-paid-ads-ga-basic", title: "Paid Ads Google Analytics - Basic Analytics", icon: FileText, type: "file" },
      { id: "recipe-paid-ads-ga-campaign", title: "Paid Ads Google Analytics - Campaign Performance", icon: FileText, type: "file" },
      { id: "recipe-int-tiktok-preview", title: "Int TikTok Ads Preview Prep", icon: FileText, type: "file" },
      { id: "recipe-meta-ads-funnel", title: "Meta Ads Conversion Funnel", icon: FileText, type: "file" },
      { id: "recipe-linkedin-lead-quality", title: "LinkedIn Lead Quality Score", icon: FileText, type: "file" },
    ]},
    { id: "recipe-google-ads", title: "Google Ads", icon: FolderOpen, type: "folder", children: [
      { id: "recipe-gads-keyword-perf", title: "Google Ads Keyword Performance", icon: FileText, type: "file" },
      { id: "recipe-gads-campaign-roas", title: "Google Ads Campaign ROAS", icon: FileText, type: "file" },
      { id: "recipe-gads-search-terms", title: "Google Ads Search Terms Analysis", icon: FileText, type: "file" },
      { id: "recipe-gads-audience-insights", title: "Google Ads Audience Insights", icon: FileText, type: "file" },
    ]},
    { id: "recipe-weekly-kpi-rollup", title: "Weekly KPI Rollup", icon: FileText, type: "file" },
    { id: "recipe-customer-ltv", title: "Customer Lifetime Value", icon: FileText, type: "file" },
    { id: "recipe-spend-vs-revenue", title: "Spend vs Revenue Summary", icon: FileText, type: "file" },
    { id: "recent-recipes-section", title: "Recent", type: "section" },
    { id: "recent-recipe-paid-ads-ga-basic", title: "Paid Ads Google Analytics - Basic Analytics", icon: FileText, type: "file" },
    { id: "recent-recipe-gads-keyword-perf", title: "Google Ads Keyword Performance", icon: FileText, type: "file" },
  ],
  "data-governance": [
    { id: "naming-convention", title: "Naming Convention", icon: BookOpen, type: "file" },
    { id: "rules", title: "Rules", icon: Shield, type: "file" },
    { id: "mission-control", title: "Mission Control", icon: Compass, type: "file" },
  ],
  "admin": [
    { id: "service-desk", title: "Service Desk", icon: Settings, type: "file" },
    { id: "dataflow", title: "Dataflow", icon: Database, type: "file" },
    { id: "billing", title: "Billing", icon: Users, type: "file" },
  ],
}

export const WORKSPACES = [
  {
    id: "business",
    name: "Business",
  },
  {
    id: "personal",
    name: "Personal",
  },
  {
    id: "agency",
    name: "Agency",
  },
] as const
